# Generated by Django 4.0.5 on 2022-06-27 07:38

import accounts.fields
import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', accounts.fields.LowerCaseEmailField(max_length=254, unique=True, validators=[accounts.validators.email_validator], verbose_name='Email Address')),
                ('username', accounts.fields.LowerCaseCharField(max_length=50, unique=True, validators=[accounts.validators.username_validator], verbose_name='username')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full Name')),
                ('profile_pic', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
