# Generated by Django 4.0.5 on 2022-06-27 14:49

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to=accounts.utils.upload_img_url),
        ),
    ]
