# Generated by Django 4.0.5 on 2022-06-30 12:54

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=accounts.utils.upload_img_url),
        ),
    ]
