# Generated by Django 4.0.5 on 2022-07-18 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_contact_follower_alter_contact_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='follower',
            new_name='following_user_id',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='following',
            new_name='user_id',
        ),
    ]
